apiVersion: v1
kind: ReplicationController
metadata:
  name: myalpine-pc
spec:
  replicas: 2
  selector:
    app: myalpine
  template:
    metadata:
      name: myalpine
      labels:
        app: myalpine
    spec:
      containers:
        - name: myalpine-container
          image: alpine
          ports:
            - containerPort: 80
