apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 3
  selector:
    app: mynginx
    version: 2.6.1
  template:
    metadata:
      name: mynginx
      labels:
        app: mynginx
        version: 2.6.1
    spec:
      containers:
        - name: mynginx-container
          image: nginx
          ports:
            - containerPort: 80
