apiVersion: v1
kind: ReplicationController
metadata:
  name: myonlineapp-rc
spec:
  replicas: 3
  selector:
    app: myonlineapp
    version: 2.6.1
  template:
    metadata:
      name: myonlineapp
      labels:
        app: myonlineapp
        version: 2.6.1
    spec:
      containers:
        - name: myonlineapp-container
          image: maha4iac/myonliineapp:1
          ports:
            - containerPort: 8080
