apiVersion: v1
kind: Service
metadata:
  name: myonlineapp-svc
  labels:
    app: myonlineapp
    version: 2.6.1
spec:
  type: NodePort
  selector:
    app: myonlineapp
    version: 2.6.1
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
    protocol: TCP
