apiVersion: v1
kind: Service
metadata:
  name: mynginx-pc
  labels:
    app: mynginx
spec:
  selector:
    app: mynginx
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
